<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>2.0.0</Version>
    <Authors>Kyle Manuel</Authors>
    <Company>Antares, LLC</Company>
    <PackageProjectUrl>https://github.com/kylepmanuel/nlighttemplate</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>template email stringtemplate</PackageTags>
    <Description>NLightTemplate is a lightweight string template renderer with a simple syntax similar to C# 6 interpolation.</Description>
    <Copyright>© 2017 Antares, LLC</Copyright>
    <IncludeDocumentationProjectOutputGroup>True</IncludeDocumentationProjectOutputGroup>
  </PropertyGroup>

  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\NLightTemplate.xml</DocumentationFile>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

</Project>
